export const INIT_USER = 'INIT_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';

export const INIT_BOOKLIST = 'INIT_BOOKLIST';
export const BOOKS_LOADING = 'BOOKS_LOADING';
export const BOOKS_FAILED = 'BOOKS_FAILED';

export const INIT_MESSAGES = 'INIT_MESSAGES';
export const MESSAGES_FAILED = 'MESSAGES_FAILED';
export const MESSAGES_LOADING = 'MESSAGES_LOADING';